# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Ragashree M C
title: Solutions Engineer
website: www.github.com/ragashreeshekar/ragashreeshekar.github.io

# Social links
github_username:  ragashreeshekar
instagram_username: ragashreeshekar
linkedin_username: ragashree-mc

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am Ragashree and I'm a Solutions Engineer with Hewlett Packard Enterprise. In addition to administrating systems and developing solutions, I also have experience in developing software and web apps. 

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Non-profit Volunteering for women empowerment and animal welfare causes.
   - Cooking
   - Reading fiction & Non-fiction

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
